apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: backend
  namespace: argocd
spec:
  description: Project for in which to deploy infra related assets 
  sourceRepos:
  - 'https://github.com/Kubical-DevOps/eccenca-test.git'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: 'backend'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
